name:                juniper
version:             0.3.0
github:              "seanhess/juniper"
license:             BSD3
author:              "Sean Hess"
maintainer:          "seanhess@gmail.com"
copyright:           "All Rights Reserved"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/seanhess/juniper#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- base64
- binary
- bytestring
- containers
- data-default
- file-embed
- http-types
- lens
- lucid
- lifted-base
- megaparsec
- mtl
- monad-loops
- websockets
- network
- network-uri
- raw-strings-qq
- scotty
- stm
- string-conversions
- tagged
- text
- time
- unordered-containers
- url
- uri-encode
- uuid
- vector
- wai
- wai-middleware-static

ghc-options:
  - -Wincomplete-patterns
  - -Wdodgy-exports
  - -Wdodgy-imports
  - -Wincomplete-record-updates
  - -Wname-shadowing
  - -fdefer-typed-holes

default-extensions:
  - ApplicativeDo
  - DataKinds
  - DeriveGeneric
  - DerivingStrategies
  - DeriveAnyClass
  - DefaultSignatures
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - QuasiQuotes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - UndecidableInstances
  - PolyKinds

library:
  source-dirs: src

executables:
  juniper-exe:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -Wall
    dependencies:
    - record-dot-preprocessor
    - record-hasfield
    - juniper

tests:
  juniper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - juniper
